// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2odgqORSvVw6t3WTDuMPTh_ySsxJme4',
    appId: '1:780313574435:web:1ad3c562f8b50df9e88596',
    messagingSenderId: '780313574435',
    projectId: 'fir-d8f15',
    authDomain: 'fir-d8f15.firebaseapp.com',
    storageBucket: 'fir-d8f15.appspot.com',
    measurementId: 'G-VB5BZ9NHVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxygoQBat_0ULMtwzQ-q8WkO1J-BuFJpI',
    appId: '1:780313574435:android:fc5e94325973c575e88596',
    messagingSenderId: '780313574435',
    projectId: 'fir-d8f15',
    storageBucket: 'fir-d8f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlI7ksChSDPZQVHiHlUJyIGZwg2ZkfpJw',
    appId: '1:780313574435:ios:618e19eb3b6b1427e88596',
    messagingSenderId: '780313574435',
    projectId: 'fir-d8f15',
    storageBucket: 'fir-d8f15.appspot.com',
    androidClientId: '780313574435-91hvea7baqf2ag4f5r21fgf1e56tnac8.apps.googleusercontent.com',
    iosClientId: '780313574435-r0ph6b47f66uk6cnl50kr21ntoqfl3ns.apps.googleusercontent.com',
    iosBundleId: 'com.chikista.chikista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvGbZylV5-06m8QXa1642KVlciefG1uUo',
    appId: '1:780313574435:web:af1a813a644bd588e88596',
    messagingSenderId: '780313574435',
    projectId: 'fir-d8f15',
    authDomain: 'fir-d8f15.firebaseapp.com',
    storageBucket: 'fir-d8f15.appspot.com',
    measurementId: 'G-1DPY9MQ5F7',
  );
}
